// Code generated by MockGen. DO NOT EDIT.
// Source: dao.go

// Package simulationsmocks is a generated GoMock package.
package simulationsmocks

import (
	context "context"
	reflect "reflect"

	simulations "github.com/emstoppel/microservices-arch/simulation"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Dao interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetSimulation mocks base method.
func (m *MockStorage) Get(ctx context.Context, simulationID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", ctx, simulationID)
}

// GetSimulation indicates an expected call of GetSimulation.
func (mr *MockStorageMockRecorder) GetSimulation(ctx, simulationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), ctx, simulationID)
}

// SaveSimulation mocks base method.
func (m *MockStorage) Save(ctx context.Context, simulation simulations.SimulationSetup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", ctx, simulation)
}

// SaveSimulation indicates an expected call of SaveSimulation.
func (mr *MockStorageMockRecorder) SaveSimulation(ctx, simulation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorage)(nil).Save), ctx, simulation)
}
