// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go

// Package simulationsmocks is a generated GoMock package.
package simulationsmocks

import (
	context "context"
	reflect "reflect"

	simulations "github.com/emstoppel/microservices-arch/simulation"
	gomock "github.com/golang/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetSimulation mocks base method.
func (m *MockGateway) Get(ctx context.Context, simulationID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", ctx, simulationID)
}

// GetSimulation indicates an expected call of GetSimulation.
func (mr *MockGatewayMockRecorder) GetSimulation(ctx, simulationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGateway)(nil).Get), ctx, simulationID)
}

// SaveSimulation mocks base method.
func (m *MockGateway) Save(ctx context.Context, request simulations.SimulationSetup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", ctx, request)
}

// SaveSimulation indicates an expected call of SaveSimulation.
func (mr *MockGatewayMockRecorder) SaveSimulation(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGateway)(nil).Save), ctx, request)
}
